# Generated by Django 4.1.5 on 2023-02-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
